FROM python:3.9

RUN mkdir /app
WORKDIR /app
COPY ./ /app/

RUN apt update -y
RUN apt upgrade -y 
RUN apt install python3-pip python3-dev build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev -y
# specific requirements REQ
RUN pip install -r requirements/dev.txt   

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8000

CMD [ "gunicorn", "django_docker_ex.wsgi:application",  "--name", "django_docker_ex.conf", "--workers=2" "--bind=0.0.0.0:8000", "--reload" ]
