FROM --platform=linux/amd64 python:3.9-slim

RUN mkdir /app
WORKDIR /app

RUN apt update -y && \
    apt upgrade -y && \
    apt install python3-pip python3-dev build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev -y
